<?php
require __DIR__ . '/bootstrap.php';
$instanceId=(int)($_GET['instance_id']??0);
if(!$instanceId) exit('Instância obrigatória.');
$auth->requireInstanceAccess($instanceId);
$appointments=$financial->appointments($instanceId);
$message=$error=null;
if($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='create'){
    try{
        $stmt=$pdo->prepare('INSERT INTO financial_service_appointments (instance_id, appointment_date, client_name, service_name, expected_amount, signal_amount, remaining_amount, status, source, external_provider, external_appointment_id, client_id, lead_id, notes, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)');
        $remaining = max(0, (float)$_POST['expected_amount'] - (float)$_POST['signal_amount']);
        $stmt->execute([$instanceId, $_POST['appointment_date'], trim($_POST['client_name']), trim($_POST['service_name']), (float)$_POST['expected_amount'], (float)$_POST['signal_amount'], $remaining, $_POST['status'], $_POST['source'], $_POST['external_provider']?:null, $_POST['external_appointment_id']?:null, null, null, trim($_POST['notes']??''), date('Y-m-d H:i:s'), date('Y-m-d H:i:s')]);
        $message='Agendamento criado.';
    }catch(Throwable $e){$error=$e->getMessage();}
}
?><!doctype html><html lang="pt-br"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Agenda/Receita</title><link rel="stylesheet" href="<?= e(base_path('assets/ui.css')) ?>"></head><body><div class="wrap"><?php financial_nav($instanceId,'appointments'); ?><div class="card"><h1 class="headline">Agenda e receita prevista</h1><p class="muted">Módulo opcional. Se você não usar CRM, pode cadastrar manualmente aqui. Se usar CRM, use os campos de `source` e `external_*` para vincular sem travar o sistema.</p><?php if($message):?><div class="toast good"><?= e($message) ?></div><?php endif; if($error):?><div class="toast bad"><?= e($error) ?></div><?php endif; ?><form method="post" class="split"><input type="hidden" name="action" value="create"><label>Data<input type="date" name="appointment_date" value="<?= date('Y-m-d') ?>"></label><label>Cliente<input type="text" name="client_name"></label><label>Serviço<input type="text" name="service_name"></label><label>Previsto<input type="number" step="0.01" name="expected_amount"></label><label>Sinal<input type="number" step="0.01" name="signal_amount" value="0"></label><label>Status<select name="status"><option>planned</option><option>confirmed</option><option>done</option><option>canceled</option></select></label><label>Origem<select name="source"><option>manual</option><option>crm</option></select></label><label>CRM/Provider<input type="text" name="external_provider" placeholder="crm, lead, agenda..."></label><label>ID externo<input type="text" name="external_appointment_id"></label><label>Observações<input type="text" name="notes"></label><button class="btn btn-primary">Salvar</button></form></div><div class="card"><div class="list"><?php foreach($appointments as $a): ?><div class="member"><div class="meta"><strong><?= e($a['client_name']) ?> · <?= e($a['service_name']) ?></strong><span class="muted"><?= e($a['appointment_date']) ?> · <?= e($a['status']) ?> · origem <?= e($a['source']) ?></span></div><span class="tag">R$ <?= number_format((float)$a['expected_amount'],2,',','.') ?></span></div><?php endforeach; ?></div></div></div></body></html>
